# Generated by Django 3.2.10 on 2022-06-22 12:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.IntegerField()),
                ('subject', models.CharField(max_length=100)),
                ('applying_for', models.CharField(choices=[('Health Science Courses', 'Health Science Courses'), ('Engineering Courses', 'Engineering Courses'), ('Management Courses', 'Management Courses'), ('Certified Courses', 'Certified Courses'), ('Other Courses', 'Other Courses')], max_length=50)),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.CharField(max_length=100)),
                ('phone', models.IntegerField()),
                ('query', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Course_desc',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=100)),
                ('pre_requisite', models.CharField(max_length=100)),
                ('duration', models.CharField(max_length=100)),
                ('fee', models.CharField(max_length=100)),
                ('breif_desc', models.CharField(max_length=100)),
                ('branch', models.CharField(choices=[('Health Science Courses', 'Health Science Courses'), ('Engineering Courses', 'Engineering Courses'), ('Management Courses', 'Management Courses'), ('Certified Courses', 'Certified Courses')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enrollment_no', models.CharField(max_length=50, unique=True)),
                ('name', models.CharField(max_length=50)),
                ('father_name', models.CharField(max_length=50)),
                ('course', models.CharField(max_length=50)),
                ('specialization', models.CharField(max_length=50)),
                ('academic_year', models.CharField(max_length=50)),
                ('year_of_passing', models.IntegerField()),
                ('profile_pic', models.ImageField(blank=True, upload_to='uploads/student_images/')),
            ],
        ),
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('particular', models.CharField(max_length=100)),
                ('max_marks', models.IntegerField()),
                ('min_marks', models.IntegerField()),
                ('obtained', models.IntegerField()),
                ('remarks', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail')], max_length=50)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.profile')),
            ],
        ),
    ]
