# Generated by Django 3.2.10 on 2022-06-24 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0003_auto_20220623_2308'),
    ]

    operations = [
        migrations.AlterField(
            model_name='admitcard',
            name='instruction',
            field=models.TextField(default="Instructions to the Candidate\n\n1. This Admit Card must be presented for verification at the time of examination, along with at least one original (not photocopied or scanned copy) and valid (not expired) photo identification card (eg: College ID, Employer ID. Driving License, Passport, PAN card, Voter ID, Aadhaar-UID, etc).\n\n2. This Admit Card is valid only if the candidate's photograph and signature images are legibly printed. Print this on an A4 sized paper using a laser printer, preferably a colour photo printer.\n\n3. Candidates should occupy their allotted seats 25 minutes before the scheduled start of the examination.\n\n4. Candidates will not be allowed to enter examination hall 30 minutes after the commencement of the  examination.\n5. Candidates will not be allowed to leave the examination hall before the end of the examination\n\n6. Bring two (2) black ink ballpoint pens. Candidates have to answer in the Optical Response Sheet (ORS) by darkening the bubbles using only a black ink ballpoint pen. Since bubbles darkened by the black ink ballpoint pen cannot be erased, candidates should darken the bubbles in the ORS very carefully.\n\n7. Name of the candidate. Registration number. Examination centre and Signature of the candidate should be entered in the ORS using only a black ink ballpoint pen.\n\n8. Calculator is allowed in the examination hall. However, shanng of calculators is NOT ALLOWED. D not bring any Charts/Tables/Loose sheets to the examination hall\n\n9. Mobile phones or any other Electronic gadgets are NOT ALLOWED inside the examination hall. There may not be any facility for safe keeping of your gadget outside the hall, sot me be easier to leave it at your residence')\n"),
        ),
    ]
