# Generated by Django 3.2.10 on 2022-07-04 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0005_resultstylehideunhide'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteDown',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display', models.BooleanField(default=False)),
            ],
        ),
    ]
