# Generated by Django 4.0.1 on 2022-08-17 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0006_sitedown'),
    ]

    operations = [
        migrations.AddField(
            model_name='idcard',
            name='course_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
