# Generated by Django 4.0.1 on 2022-08-19 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('student', '0010_rename_studentadmitcard_admitcard'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='admitcard',
            name='date',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='subject_name',
        ),
        migrations.RemoveField(
            model_name='admitcard',
            name='time',
        ),
        migrations.CreateModel(
            name='AdmitcardExmDetail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject_name', models.CharField(max_length=100)),
                ('date', models.DateField()),
                ('time', models.CharField(max_length=100)),
                ('admitcard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='student.admitcard')),
            ],
        ),
    ]
